server:
  port: 8090
spring:
 devtools:
  restart:
  enabled: true   #热部署
 datasource:
  username: root
  password: hm123
  url: jdbc:mysql://127.0.0.1:3306/clown?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
  driver-class-name: com.mysql.cj.jdbc.Driver
#   数据源基本配置
#  type: com.alibaba.druid.pool.DruidDataSource
# 数据源其他配置
  initialSize: 5    #连接池初始数量
  minIdle: 5        #最大空闲数，数据库连接的最大空闲时间。超过空闲时间，数据库连接将被标记为不可用，然后被释放。设为0表示无限制。
  maxActive: 20     #最大连接数
  maxWait: 60000    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示
  testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
  testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。 默认true
  testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
  poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。

# mybatis
mybatis:
 mapper-locations: classpath*:com/hm/**/mapper/*.xml
 type-aliases-package: com.hm.*.*.model
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #这个是可以打印sql、参数、查询结果的

redis:
 host: localhost
 port: 6379